<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users_model extends MAX_Model
{

    public $table = 'auth_login';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('accnt_create_time', $q);
	$this->db->or_like('account_type', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('email_ver_time', $q);
	$this->db->or_like('email_verification_link', $q);
	$this->db->or_like('email_verified', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('passwd_reset_str', $q);
	$this->db->or_like('passwd_reset_time', $q);
	$this->db->or_like('password_hash', $q);
	$this->db->or_like('surname', $q);
	$this->db->or_like('username', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('accnt_create_time', $q);
	$this->db->or_like('account_type', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('email_ver_time', $q);
	$this->db->or_like('email_verification_link', $q);
	$this->db->or_like('email_verified', $q);
	$this->db->or_like('first_name', $q);
	$this->db->or_like('passwd_reset_str', $q);
	$this->db->or_like('passwd_reset_time', $q);
	$this->db->or_like('password_hash', $q);
	$this->db->or_like('surname', $q);
	$this->db->or_like('username', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Cangsalak Codeigniter CRUD Generator 2023-03-21 01:22:24 */