<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$lang['create'] = 'สร้างใหม่';
$lang['update'] = 'แก้ไข';
$lang['delete'] = 'ลบ';
$lang['Read'] = 'อ่าน';
$lang['Change'] = 'แก้ไข';
$lang['Delete'] = 'ลบ';
$lang['Are you sure you want to delete this?'] = 'คุณแน่ใจหรือไม่ว่าต้องการลบสิ่งนี้';
$lang['Hapus'] = 'ตกลง';
$lang['submit'] = 'ตกลง';
$lang['Total'] = 'ทั้งหมด';
$lang['Excel'] = 'Excel';
$lang['Word'] = 'Word';
$lang['PDF'] = 'PDF';
$lang['Add Data'] = 'เพิ่มข้อมูล';
$lang['Search'] = 'ค้นหา';
$lang['No'] = 'ลำดับ';
$lang['Action'] = 'การกระทำ';
$lang['Cancelled'] = 'ยกเลิก';



/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Cangsalak Codeigniter CRUD Generator 2023-03-21 01:22:24 */