<?php 

$string = "<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

\$lang['create'] = 'create';
\$lang['update'] = 'update';
\$lang['delete'] = 'delete';
\$lang['Read'] = 'Read';
\$lang['Change'] = 'Change';
\$lang['Delete'] = 'Delete';
\$lang['Are you sure you want to delete this?'] = 'Are you sure you want to delete this?';
\$lang['Hapus'] = 'Hapus';
\$lang['submit'] = 'submit';
\$lang['Total'] = 'Total';
\$lang['Excel'] = 'Excel';
\$lang['Word'] = 'Word';
\$lang['PDF'] = 'PDF';
\$lang['Add Data'] = 'Add Data';
\$lang['Search'] = 'Search';
\$lang['No'] = 'No';
\$lang['Action'] = 'Action';
\$lang['Cancelled'] = 'Cancelled';



/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Cangsalak Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */";



$hasil_language_en = createFile($string, $target."language/en/app_lang.php");

?>