<?php

$string = "<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require(APPPATH.'/libraries/REST_Controller.php');
class " . $c . "_api extends REST_Controller
{";

$string .= "\n\n    
        public function __construct() {
            parent::__construct();
            \$this->load->model('" . $c . "_model',rest_api);
        }    
        public function " . $c . "_get(){
           \$r = \$this->load->model('$m');
           \$this->response(\$r); 
        }
        public function " . $c . "_put(){
           \$id = \$this->uri->segment(3);

           \$data = array(";
            foreach ($non_pk as $row) {
                $string .= "\n\t\t'" . $row['column_name'] . "' => \$this->input->post('" . $row['column_name'] . "',TRUE),";
            }
            $string .= "\n\t    );

            \$r = \$this->rest_api->update(\$id,\$data);
               \$this->response(\$r); 
        }

       public function " . $c . "_post(){
           \$data = array(";
            foreach ($non_pk as $row) {
                $string .= "\n\t\t'" . $row['column_name'] . "' => \$this->input->post('" . $row['column_name'] . "',TRUE),";
            }
            $string .= "\n\t    );
           \$r = \$this->rest_api->insert(\$data);
           \$this->response(\$r); 
       }
       public function " . $c . "_delete(){
           \$id = \$this->uri->segment(3);
           \$r = \$this->rest_api->delete(\$id);
           \$this->response(\$r); 
       }
    

}";

    $string .= "\n\n}\n\n/* End of file $c_file */
    /* Location: ./application/modules/" . $c . "/controllers/$c_file */
    /* Please DO NOT modify this information : */
    /* Generated by Cangsalak Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */";




    $hasil_controller_rest_api = createFile($string, $target . "controllers/" . $c_file);

?>