<?php 

$string = "<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

\$lang['create'] = 'สร้างใหม่';
\$lang['update'] = 'แก้ไข';
\$lang['delete'] = 'ลบ';
\$lang['Read'] = 'อ่าน';
\$lang['Change'] = 'แก้ไข';
\$lang['Delete'] = 'ลบ';
\$lang['Are you sure you want to delete this?'] = 'คุณแน่ใจหรือไม่ว่าต้องการลบสิ่งนี้';
\$lang['Hapus'] = 'ตกลง';
\$lang['submit'] = 'ตกลง';
\$lang['Total'] = 'ทั้งหมด';
\$lang['Excel'] = 'Excel';
\$lang['Word'] = 'Word';
\$lang['PDF'] = 'PDF';
\$lang['Add Data'] = 'เพิ่มข้อมูล';
\$lang['Search'] = 'ค้นหา';
\$lang['No'] = 'ลำดับ';
\$lang['Action'] = 'การกระทำ';
\$lang['Cancelled'] = 'ยกเลิก';
\$lang['Close'] = 'ปิด';



/* End of file pagination.php */
/* Location: ./application/modules/" . $c . "/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Cangsalak Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */";



$hasil_language_th = createFile($string, $target."language/th/app_lang.php");

?>